import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import AxiosController from "@/lib/axios-controller";
import { getAllHeaders } from "@/lib/utils";
import { User } from "@/lib/types";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticketing App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  let currentUser;
  try {
    const data = await AxiosController.ssr.get<User>("/api/users/currentuser", {
      headers: getAllHeaders(headersList),
    });
    currentUser = data.currentUser;
  } catch (error) {
    console.log(error);
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
